### ISSUE TITLE
Making a prototype

### ISSUE THREAD

**Issue by Oraxien40** [AIESydneyStudents/DIGITAL_BASKET#54]
- [x] put in the player #19
- [x] put in collectable Asset
- [x] put in the enemy #11
- [x] put in trap #2
- [x] add pickup and drop off to the player #21 #22
- [x] #58 
- [x] add placeholder shelf #31
- [x] add placeholder cold shelf #7
- [x] add placeholder stands #10
- [x] win condition
- [x] loss condition
